name: build and test
run-name: build and test app

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with: 
                java-version: 17
                distribution: microsoft
                server-id: github
                cache: maven
                cache-dependency-path: ./demo-service/pom.xml
            - name: Build application
              working-directory: ./demo-service
              run: mvn clean verify --file pom.xml --batch-mode -Dmin.coverage=0.00
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with: 
                name: demo-service-artifact
                path: ${{github.workspace}}/target/*.jar
